"""add school logo and theme color

Revision ID: 7e8d137f7152
Revises: c3825d72fd27
Create Date: 2026-10-01 06:51:40.666252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8d137f7152'
down_revision = 'c3825d72fd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('theme_color', sa.String(length=7), nullable=False, server_default='#4f46e5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('theme_color')
        batch_op.drop_column('logo_filename')

    # ### end Alembic commands ###
