"""add mfa and lockout columns to users

Revision ID: 8f56069f02a2
Revises: d5df2a1c72b1
Create Date: 2026-10-02 05:39:00.678309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f56069f02a2'
down_revision = 'd5df2a1c72b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('mfa_method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mfa_totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('mfa_backup_codes', sa.Text(), nullable=True))

    # SQLite's batch mode bakes the server_default into the recreated table;
    # drop it afterward so it doesn't linger as an implicit default for
    # columns the model always sets explicitly going forward.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts', server_default=None)
        batch_op.alter_column('mfa_enabled', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_backup_codes')
        batch_op.drop_column('mfa_totp_secret')
        batch_op.drop_column('mfa_method')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
